# Generated by Django 5.2.18 on 2026-10-06 20:09

import core.constraints
import django.db.models.deletion
import django.db.models.functions.math
import django.db.models.lookups
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0001_initial'),
        ('rounds', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('self_reported_minutes', models.PositiveSmallIntegerField(help_text='What they say they attended. Only used when there is no attendance record.')),
                ('attestation', models.BooleanField(help_text='They confirm the minutes are accurate.')),
                ('is_complete', models.BooleanField(default=False, help_text='All required objective questions are answered.')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaluations', to='people.person')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaluations', to='rounds.session')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='EvaluationResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question_key', models.CharField(help_text='Stable across years, so reports compare like with like.', max_length=100)),
                ('rating', models.SmallIntegerField(blank=True, null=True)),
                ('free_text', models.TextField(blank=True, null=True)),
                ('objective', models.ForeignKey(blank=True, help_text='Blank for general questions.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='responses', to='rounds.learningobjective')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='credits.evaluationsubmission')),
            ],
        ),
        migrations.CreateModel(
            name='CreditAdjustment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('delta_credits', models.DecimalField(decimal_places=2, help_text='Added to the computed credit. Negative to take away. Steps of 0.25.', max_digits=5, validators=[core.constraints.validate_quarter_multiple])),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_adjustments', to='rounds.roundsevent')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_adjustments', to='people.person')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('reason', ''), _negated=True), name='creditadjustment_needs_reason'), models.CheckConstraint(condition=models.Q(('delta_credits', 0), _negated=True), name='creditadjustment_not_zero'), models.CheckConstraint(condition=django.db.models.lookups.Exact(django.db.models.functions.math.Mod(models.F('delta_credits'), models.Value(Decimal('0.25'), output_field=models.DecimalField(decimal_places=2, max_digits=5)), output_field=models.DecimalField(decimal_places=2, max_digits=5)), models.Value(Decimal('0'), output_field=models.DecimalField(decimal_places=2, max_digits=5))), name='creditadjustment_quarter_multiple')],
            },
        ),
        migrations.AddConstraint(
            model_name='evaluationsubmission',
            constraint=models.UniqueConstraint(fields=('person', 'session'), name='evaluationsubmission_one_per_session'),
        ),
        migrations.AddConstraint(
            model_name='evaluationsubmission',
            constraint=models.CheckConstraint(condition=models.Q(('attestation', True)), name='evaluationsubmission_attested'),
        ),
        migrations.AddConstraint(
            model_name='evaluationresponse',
            constraint=models.UniqueConstraint(fields=('submission', 'question_key', 'objective'), name='evaluationresponse_one_answer_per_question', nulls_distinct=False),
        ),
    ]
