# Generated by Django 5.2.18 on 2026-10-07 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0002_evaluation_windows'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='creditadjustment',
            name='creditadjustment_quarter_multiple',
        ),
        migrations.AlterField(
            model_name='creditadjustment',
            name='delta_credits',
            field=models.DecimalField(decimal_places=2, help_text='Added to the computed credit. Negative to take away.', max_digits=5),
        ),
    ]
