# Generated by Django 5.2.18 on 2026-10-07 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0003_adjustments_any_hundredth'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditadjustment',
            name='kind',
            field=models.CharField(choices=[('attendance', 'Attendance'), ('teaching', 'Teaching')], default='attendance', help_text='Which kind of credit this changes. They are never blended.', max_length=20),
        ),
    ]
