# Generated by Django 5.2.18 on 2026-10-07 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0007_form_version_required'),
        ('people', '0004_magic_links'),
        ('rounds', '0010_evaluation_form'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='evaluationsubmission',
            name='evaluationsubmission_attested',
        ),
        migrations.AddField(
            model_name='evaluationquestion',
            name='required_when',
            field=models.JSONField(blank=True, help_text='Required only when another question has a given answer: {"question_key": "commercial_bias", "value": 0}. Free-text questions only.', null=True),
        ),
        migrations.AlterField(
            model_name='evaluationquestion',
            name='required',
            field=models.BooleanField(default=True, editable=False),
        ),
        migrations.AlterField(
            model_name='evaluationsubmission',
            name='attestation',
            field=models.BooleanField(default=False, help_text='They confirm the minutes are accurate. Part of what makes it complete.'),
        ),
        migrations.AlterField(
            model_name='evaluationsubmission',
            name='self_reported_session_minutes',
            field=models.PositiveSmallIntegerField(blank=True, help_text='How long they say they attended this session. Only used when there is no attendance record. Blank on a draft.', null=True),
        ),
        migrations.AddConstraint(
            model_name='evaluationsubmission',
            constraint=models.CheckConstraint(condition=models.Q(('is_complete', False), models.Q(('attestation', True), ('self_reported_session_minutes__isnull', False)), _connector='OR'), name='evaluationsubmission_complete_is_attested'),
        ),
    ]
