# Generated by Django 5.2.18 on 2026-10-07 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0009_evaluation_gate_and_statement'),
        ('people', '0004_magic_links'),
        ('rounds', '0010_evaluation_form'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='evaluationsubmission',
            name='evaluationsubmission_complete_is_attested',
        ),
        migrations.AddConstraint(
            model_name='evaluationsubmission',
            constraint=models.CheckConstraint(condition=models.Q(('is_complete', False), ('session__isnull', True), models.Q(('attestation', True), ('self_reported_session_minutes__isnull', False)), _connector='OR'), name='evaluationsubmission_complete_is_attested'),
        ),
    ]
