# Generated by Django 5.2.18 on 2026-10-06 20:04

import core.constraints
import django.core.validators
import django.db.models.deletion
import django.db.models.functions.math
import django.db.models.lookups
import django.utils.timezone
import rounds.models
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='COIDeclaration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('has_conflict', models.BooleanField()),
                ('details', models.TextField(blank=True, help_text='Required when there is a conflict.')),
                ('declared_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('valid_until', models.DateField(default=rounds.models.end_of_academic_year)),
                ('disclosure_text_version', models.CharField(help_text='Which version of the statement was agreed to.', max_length=50)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='coi_declarations', to='people.person')),
            ],
            options={
                'verbose_name': 'COI declaration',
                'ordering': ['-declared_at'],
            },
        ),
        migrations.CreateModel(
            name='RoundsEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default=rounds.models.default_event_title, help_text='Prints on certificate lines.', max_length=200)),
                ('date', models.DateField()),
                ('start_at', models.DateTimeField(help_text='Scheduled start.')),
                ('end_at', models.DateTimeField(help_text='Scheduled end.')),
                ('actual_start_at', models.DateTimeField(blank=True, help_text='Only if it differed. Blank means as scheduled.', null=True)),
                ('actual_end_at', models.DateTimeField(blank=True, help_text="Set this when rounds ran over and everyone's credit follows.", null=True)),
                ('teams_join_url', models.URLField(blank=True, max_length=2000)),
                ('teams_meeting_id', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('held', 'Held'), ('closed', 'Closed')], default='draft', max_length=10)),
                ('accredited_credits', models.DecimalField(decimal_places=2, help_text='Credits available for the whole event, in steps of 0.25.', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), core.constraints.validate_quarter_multiple])),
            ],
            options={
                'ordering': ['-date'],
                'constraints': [models.CheckConstraint(condition=models.Q(('end_at__gt', models.F('start_at'))), name='roundsevent_ends_after_start'), models.CheckConstraint(condition=models.Q(('accredited_credits__gte', 0)), name='roundsevent_credits_not_negative'), models.CheckConstraint(condition=django.db.models.lookups.Exact(django.db.models.functions.math.Mod(models.F('accredited_credits'), models.Value(Decimal('0.25'), output_field=models.DecimalField(decimal_places=2, max_digits=5)), output_field=models.DecimalField(decimal_places=2, max_digits=5)), models.Value(Decimal('0'), output_field=models.DecimalField(decimal_places=2, max_digits=5))), name='roundsevent_credits_quarter_multiple')],
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('position', models.PositiveSmallIntegerField(help_text='1, 2, 3. Order on the flyer.')),
                ('title', models.CharField(max_length=300)),
                ('duration_minutes', models.PositiveSmallIntegerField()),
                ('draft_blurb', models.TextField(blank=True)),
                ('published_blurb', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(blank=True, help_text="Blank means the presenters haven't filled it in yet.", null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='rounds.roundsevent')),
            ],
            options={
                'ordering': ['event', 'position'],
            },
        ),
        migrations.CreateModel(
            name='LearningObjective',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('position', models.PositiveSmallIntegerField()),
                ('text', models.TextField()),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objectives', to='rounds.session')),
            ],
            options={
                'ordering': ['session', 'position'],
            },
        ),
        migrations.CreateModel(
            name='SessionPresenter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('position', models.PositiveSmallIntegerField(default=1, help_text='Order the names print.')),
                ('coi_declaration', models.ForeignKey(blank=True, help_text="Blank picks up the presenter's current declaration, if they have one.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='session_presenters', to='rounds.coideclaration')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='presentations', to='people.person')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_presenters', to='rounds.session')),
            ],
            options={
                'ordering': ['session', 'position'],
            },
        ),
        migrations.AddField(
            model_name='session',
            name='presenters',
            field=models.ManyToManyField(related_name='sessions_presented', through='rounds.SessionPresenter', to='people.person'),
        ),
        migrations.AddConstraint(
            model_name='coideclaration',
            constraint=models.CheckConstraint(condition=models.Q(('has_conflict', False), models.Q(('details', ''), _negated=True), _connector='OR'), name='coideclaration_conflict_needs_details'),
        ),
        migrations.AddConstraint(
            model_name='learningobjective',
            constraint=models.UniqueConstraint(fields=('session', 'position'), name='learningobjective_unique_position'),
        ),
        migrations.AddConstraint(
            model_name='sessionpresenter',
            constraint=models.UniqueConstraint(fields=('session', 'person'), name='sessionpresenter_unique_person'),
        ),
        migrations.AddConstraint(
            model_name='sessionpresenter',
            constraint=models.UniqueConstraint(fields=('session', 'position'), name='sessionpresenter_unique_position'),
        ),
        migrations.AddConstraint(
            model_name='session',
            constraint=models.UniqueConstraint(fields=('event', 'position'), name='session_unique_position'),
        ),
    ]
