# Generated by Django 5.2.18 on 2026-10-07 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rounds', '0002_session_times'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roundsevent',
            name='date',
            field=models.DateField(blank=True, help_text='Blank means the day it starts.'),
        ),
        migrations.AlterField(
            model_name='roundsevent',
            name='end_at',
            field=models.DateTimeField(blank=True, help_text='Blank means three hours after the start.'),
        ),
        migrations.AlterField(
            model_name='session',
            name='start_at',
            field=models.DateTimeField(blank=True, help_text="Blank means right after the previous session, or the event's start."),
        ),
    ]
