# Generated by Django 5.2.18 on 2026-10-07 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rounds', '0003_blank_times_fill_in'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningobjective',
            name='position',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Blank takes the next number.'),
        ),
        migrations.AlterField(
            model_name='session',
            name='position',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Order on the flyer. Blank takes the next number.'),
        ),
        migrations.AlterField(
            model_name='sessionpresenter',
            name='position',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Order the names print. Blank takes the next number.'),
        ),
    ]
