# Generated by Django 5.2.18 on 2026-10-07 02:11

import django.db.models.constraints
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_person_affiliation_employer'),
        ('rounds', '0005_coi_questionnaire'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='learningobjective',
            name='learningobjective_unique_position',
        ),
        migrations.RemoveConstraint(
            model_name='session',
            name='session_unique_position',
        ),
        migrations.RemoveConstraint(
            model_name='sessionpresenter',
            name='sessionpresenter_unique_position',
        ),
        migrations.AddConstraint(
            model_name='learningobjective',
            constraint=models.UniqueConstraint(deferrable=django.db.models.constraints.Deferrable['DEFERRED'], fields=('session', 'position'), name='learningobjective_unique_position'),
        ),
        migrations.AddConstraint(
            model_name='session',
            constraint=models.UniqueConstraint(deferrable=django.db.models.constraints.Deferrable['DEFERRED'], fields=('event', 'position'), name='session_unique_position'),
        ),
        migrations.AddConstraint(
            model_name='sessionpresenter',
            constraint=models.UniqueConstraint(deferrable=django.db.models.constraints.Deferrable['DEFERRED'], fields=('session', 'position'), name='sessionpresenter_unique_position'),
        ),
    ]
