# Generated by Django 5.2.18 on 2026-10-08 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rounds', '0010_evaluation_form'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='coiresponse',
            name='coiresponse_yes_needs_details',
        ),
        migrations.AddField(
            model_name='coideclaration',
            name='activity_role',
            field=models.CharField(blank=True, choices=[('spc_member', 'Scientific planning committee member'), ('moderator', 'Moderator'), ('speaker', 'Speaker'), ('author', 'Author'), ('facilitator', 'Facilitator'), ('other', 'Other')], help_text='Role in the activity.', max_length=20),
        ),
        migrations.AddField(
            model_name='coideclaration',
            name='activity_role_other',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='coideclaration',
            name='attested',
            field=models.BooleanField(default=False, help_text="'I agree' was ticked."),
        ),
        migrations.AddField(
            model_name='coideclaration',
            name='attested_name',
            field=models.CharField(blank=True, help_text="The declarant's name as it was when they agreed.", max_length=400),
        ),
        migrations.AddField(
            model_name='coideclaration',
            name='generic_names_acknowledged',
            field=models.BooleanField(blank=True, help_text='Acknowledges the generic-names requirement. A no is flagged for the program admin.', null=True),
        ),
        migrations.AddField(
            model_name='coideclaration',
            name='has_relationships',
            field=models.BooleanField(blank=True, help_text="The form's top-level answer. No writes an explicit no to every category.", null=True),
        ),
        migrations.AddField(
            model_name='coideclaration',
            name='off_label',
            field=models.BooleanField(blank=True, help_text='Intends to recommend off-label use of medication.', null=True),
        ),
        migrations.AddField(
            model_name='coiresponse',
            name='organizations',
            field=models.TextField(blank=True, help_text='Name of for-profit or not-for-profit organization(s). Required when yes.'),
        ),
        migrations.AddField(
            model_name='coiresponse',
            name='relationship_description',
            field=models.TextField(blank=True, help_text='Description of relationship(s). Required when yes.'),
        ),
        migrations.AddField(
            model_name='sessionpresenter',
            name='coi_confirmed_at',
            field=models.DateTimeField(blank=True, help_text='When the presenter confirmed the attached declaration is still accurate for this session.', null=True),
        ),
        migrations.AlterField(
            model_name='coiresponse',
            name='details',
            field=models.TextField(blank=True),
        ),
    ]
