# Generated by Django 5.2.18 on 2026-10-08 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rounds', '0012_coi_details_to_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coiresponse',
            name='details',
        ),
        migrations.AddConstraint(
            model_name='coiresponse',
            constraint=models.CheckConstraint(condition=models.Q(('has_conflict', False), models.Q(('relationship_description', ''), _negated=True), _connector='OR'), name='coiresponse_yes_needs_description'),
        ),
        migrations.AddConstraint(
            model_name='coiresponse',
            constraint=models.CheckConstraint(condition=models.Q(('has_conflict', True), models.Q(('organizations', ''), ('relationship_description', '')), _connector='OR'), name='coiresponse_no_is_blank'),
        ),
    ]
