# Generated by Django 5.2.18 on 2026-10-06 20:11

import certificates.rules
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0001_initial'),
        ('rounds', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('certificate_type', models.CharField(choices=[('cme', 'CME credit certificate'), ('attendance', 'Attendance certificate')], max_length=20)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('total_credits', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('recipient_name', models.CharField(max_length=400)),
                ('recipient_credential', models.CharField(blank=True, max_length=50)),
                ('licence_number', models.CharField(blank=True, max_length=50)),
                ('licence_jurisdiction', models.CharField(blank=True, max_length=10)),
                ('verification_code', models.CharField(default=certificates.rules.generate_verification_code, max_length=20, unique=True)),
                ('template_version', models.CharField(max_length=50)),
                ('pdf_sha256', models.CharField(blank=True, max_length=64)),
                ('issued_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_reason', models.TextField(blank=True)),
                ('issued_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='certificates', to='people.person')),
                ('supersedes', models.OneToOneField(blank=True, help_text='The certificate this one replaces.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='superseded_by', to='certificates.certificate')),
            ],
            options={
                'ordering': ['-issued_at'],
                'permissions': [('issue_certificate', 'Can issue certificates'), ('revoke_certificate', 'Can revoke certificates')],
            },
        ),
        migrations.CreateModel(
            name='CertificateLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_title', models.CharField(max_length=200)),
                ('event_date', models.DateField()),
                ('session_titles', models.JSONField(default=list, help_text='Print-only snapshot.')),
                ('attended_minutes', models.PositiveIntegerField()),
                ('minutes_source', models.CharField(choices=[('teams', 'Teams'), ('manual', 'Manual'), ('mixed', 'Mixed'), ('self_reported', 'Self-reported')], max_length=20)),
                ('computed_credits', models.DecimalField(decimal_places=2, max_digits=5)),
                ('adjustment_credits', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('credits', models.DecimalField(decimal_places=2, max_digits=5)),
                ('certificate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='certificates.certificate')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='rounds.roundsevent')),
            ],
            options={
                'ordering': ['certificate', 'event_date'],
            },
        ),
        migrations.AddConstraint(
            model_name='certificate',
            constraint=models.CheckConstraint(condition=models.Q(('period_end__gte', models.F('period_start'))), name='certificate_period_in_order'),
        ),
        migrations.AddConstraint(
            model_name='certificate',
            constraint=models.CheckConstraint(condition=models.Q(('total_credits__gte', 0)), name='certificate_total_not_negative'),
        ),
        migrations.AddConstraint(
            model_name='certificate',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('revoked_at__isnull', True), ('revoked_reason', '')), models.Q(('revoked_at__isnull', False), models.Q(('revoked_reason', ''), _negated=True)), _connector='OR'), name='certificate_revocation_has_reason'),
        ),
        migrations.AddConstraint(
            model_name='certificate',
            constraint=models.CheckConstraint(condition=models.Q(('supersedes__isnull', True), models.Q(('supersedes', models.F('id')), _negated=True), _connector='OR'), name='certificate_does_not_supersede_itself'),
        ),
        migrations.AddConstraint(
            model_name='certificateline',
            constraint=models.UniqueConstraint(fields=('certificate', 'event'), name='certificateline_one_per_event'),
        ),
        migrations.AddConstraint(
            model_name='certificateline',
            constraint=models.CheckConstraint(condition=models.Q(('credits__gte', 0)), name='certificateline_credits_not_negative'),
        ),
    ]
