# Generated by Django 5.2.18 on 2026-10-07 02:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0003_attendance_and_teaching'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='attendance_credits',
            field=models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='teaching_credits',
            field=models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
