# Generated by Django 5.2.18 on 2026-10-07 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0006_certificate_program_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificateline',
            name='minutes_source',
            field=models.CharField(choices=[('teams', 'Teams'), ('signin_sheet', 'Sign-in sheet'), ('qr', 'QR sign-in'), ('manual', 'Manual'), ('mixed', 'Mixed'), ('self_reported', 'Self-reported')], max_length=20),
        ),
    ]
