# Generated by Django 5.2.18 on 2026-10-07 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0007_sources_and_signoff'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='accreditation_statement',
            field=models.TextField(blank=True, help_text='Snapshotted from the program when issued: names the accredited CPD provider.'),
        ),
    ]
