# Generated by Django 5.2.18 on 2026-10-06 20:11

import django.core.serializers.json
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_type', models.CharField(choices=[('staff', 'Staff'), ('attendee', 'Attendee'), ('system', 'System')], max_length=10)),
                ('actor_label', models.CharField(help_text='Who it was, in words, as of that moment. Survives a rename.', max_length=320)),
                ('action', models.CharField(max_length=100)),
                ('object_type', models.CharField(blank=True, max_length=100)),
                ('object_id', models.CharField(blank=True, max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='people.person')),
                ('actor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'audit log entry',
                'verbose_name_plural': 'audit log',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['object_type', 'object_id'], name='audit_audit_object__1f9df3_idx'), models.Index(fields=['action'], name='audit_audit_action_86e815_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('actor_person__isnull', True), ('actor_type', 'staff'), ('actor_user__isnull', False)), models.Q(('actor_person__isnull', False), ('actor_type', 'attendee'), ('actor_user__isnull', True)), models.Q(('actor_person__isnull', True), ('actor_type', 'system'), ('actor_user__isnull', True)), _connector='OR'), name='auditlog_actor_matches_type'), models.CheckConstraint(condition=models.Q(('actor_label', ''), _negated=True), name='auditlog_actor_label_set')],
            },
        ),
    ]
