# Generated by Django 5.2.18 on 2026-10-06 20:02

import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AllowedDomain',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('domain', models.CharField(max_length=253, unique=True)),
                ('auto_admit', models.BooleanField(default=True, help_text='Off means sign-ins from this domain go to the review queue.')),
                ('note', models.TextField(blank=True, help_text='Why it was added.')),
            ],
            options={
                'ordering': ['domain'],
                'constraints': [models.CheckConstraint(condition=models.Q(('domain', django.db.models.functions.text.Lower('domain'))), name='alloweddomain_domain_lowercase')],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('given_name', models.CharField(max_length=200)),
                ('family_name', models.CharField(max_length=200)),
                ('credential', models.CharField(blank=True, help_text='MD, RN, PharmD, PhD. Prints on the certificate.', max_length=50)),
                ('role', models.CharField(choices=[('physician', 'Physician'), ('nurse', 'Nurse'), ('pharmacist', 'Pharmacist'), ('trainee', 'Trainee'), ('student', 'Student'), ('other', 'Other')], max_length=20)),
                ('licence_number', models.CharField(blank=True, help_text='As entered. This is what prints on the certificate.', max_length=50, null=True)),
                ('licence_number_normalized', models.CharField(editable=False, max_length=50, null=True)),
                ('licence_jurisdiction', models.CharField(blank=True, choices=[('CMQ', 'CMQ'), ('CPSO', 'CPSO'), ('OIIQ', 'OIIQ'), ('OPQ', 'OPQ'), ('other', 'Other')], max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('merged_into', models.ForeignKey(blank=True, help_text='Set by a merge. This record is then a tombstone.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='merged_from', to='people.person')),
                ('staff_user', models.OneToOneField(blank=True, help_text='Only for a staff member who also attends.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='person', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'people',
                'ordering': ['family_name', 'given_name'],
            },
        ),
        migrations.CreateModel(
            name='PersonEmail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('verified_at', models.DateTimeField(blank=True, help_text='Set when a magic link sent to this address is used.', null=True)),
                ('is_primary', models.BooleanField(default=False, help_text='Where merge offers and certificates go.')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='emails', to='people.person')),
            ],
            options={
                'ordering': ['email'],
            },
        ),
        migrations.CreateModel(
            name='SignInRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('given_name', models.CharField(max_length=200)),
                ('family_name', models.CharField(max_length=200)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='person',
            constraint=models.UniqueConstraint(condition=models.Q(('licence_jurisdiction__isnull', False), ('licence_number_normalized__isnull', False), ('merged_into__isnull', True)), fields=('licence_jurisdiction', 'licence_number_normalized'), name='person_unique_active_licence'),
        ),
        migrations.AddConstraint(
            model_name='person',
            constraint=models.CheckConstraint(condition=models.Q(('licence_number__isnull', True), ('licence_jurisdiction__isnull', False), _connector='OR'), name='person_licence_needs_jurisdiction'),
        ),
        migrations.AddConstraint(
            model_name='person',
            constraint=models.CheckConstraint(condition=models.Q(('merged_into__isnull', True), models.Q(('merged_into', models.F('id')), _negated=True), _connector='OR'), name='person_not_merged_into_self'),
        ),
        migrations.AddConstraint(
            model_name='personemail',
            constraint=models.CheckConstraint(condition=models.Q(('email', django.db.models.functions.text.Lower('email'))), name='personemail_email_lowercase'),
        ),
        migrations.AddConstraint(
            model_name='personemail',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('person',), name='personemail_one_primary_per_person'),
        ),
        migrations.AddConstraint(
            model_name='signinrequest',
            constraint=models.CheckConstraint(condition=models.Q(('email', django.db.models.functions.text.Lower('email'))), name='signinrequest_email_lowercase'),
        ),
    ]
