# Generated by Django 5.2.18 on 2026-10-06 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['family_name', 'given_name'], 'permissions': [('merge_person', 'Can merge duplicate people')], 'verbose_name_plural': 'people'},
        ),
    ]
