# Generated by Django 5.2.18 on 2026-10-07 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_alter_person_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='affiliation',
            field=models.CharField(blank=True, help_text='Appears on the flyer and on certificates, exactly as typed. For example a university department. More than one is fine.', max_length=300),
        ),
        migrations.AddField(
            model_name='person',
            name='employer',
            field=models.CharField(blank=True, help_text='Appears on the flyer and on certificates, exactly as typed. For example a hospital or clinic. More than one is fine.', max_length=300),
        ),
    ]
