# Generated by Django 5.2.18 on 2026-10-07 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_person_affiliation_employer'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='sessions_revoked_at',
            field=models.DateTimeField(blank=True, editable=False, help_text='Set by sign out everywhere. Sessions signed in before this are dead.', null=True),
        ),
    ]
