# Generated by Django 5.2.18 on 2026-10-07 12:55

import core.constraints
import django.core.validators
import django.db.models.deletion
import django.db.models.functions.math
import django.db.models.lookups
import programs.models
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('short_name', models.SlugField(help_text='The <org> of the hostname and the deploy script.', unique=True)),
                ('website', models.URLField(blank=True, max_length=300)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(help_text='For URLs. Unique within the institution.')),
                ('series_name', models.CharField(default=programs.models.default_series_name, help_text='The default title of a new event. Prints on certificate lines.', max_length=200)),
                ('attendance_rate_per_hour', models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='Credits per hour attended. Snapshotted onto each certificate line at issue.', max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('teaching_rate_per_hour', models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='Credits per hour presented. Snapshotted onto each certificate line at issue.', max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('default_accredited_credits', models.DecimalField(decimal_places=2, default=Decimal('3.00'), help_text='Pre-filled on a new event. The accreditor-set ceiling, in steps of 0.25.', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), core.constraints.validate_quarter_multiple])),
                ('accreditation_year_end_month', models.PositiveSmallIntegerField(default=programs.models.default_year_end_month)),
                ('accreditation_year_end_day', models.PositiveSmallIntegerField(default=programs.models.default_year_end_day)),
                ('coi_question_version', models.CharField(default=programs.models.default_coi_version, help_text='Which COI questionnaire version new declarations for this program use.', max_length=50)),
                ('attendance_disagreement_minutes', models.PositiveSmallIntegerField(default=5, help_text='Attendance sources further apart than this, for one person and session, are held back from bulk sign-off for a human to look at.')),
                ('retention_years', models.PositiveSmallIntegerField(default=7, help_text='How many years records are kept after the accreditation year. The value only: what happens when it expires is still an open decision.')),
                ('is_active', models.BooleanField(default=True, help_text='A retired program keeps its history and takes no new events.')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='programs', to='programs.institution')),
            ],
            options={
                'ordering': ['institution', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProgramRole',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('coordinator', 'Coordinator'), ('program_admin', 'Program admin'), ('read_only', 'Read only')], max_length=20)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='roles', to='programs.program')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['program', 'user'],
            },
        ),
        migrations.AddConstraint(
            model_name='program',
            constraint=models.UniqueConstraint(fields=('institution', 'slug'), name='program_unique_slug'),
        ),
        migrations.AddConstraint(
            model_name='program',
            constraint=models.CheckConstraint(condition=models.Q(('attendance_rate_per_hour__gte', 0), ('teaching_rate_per_hour__gte', 0)), name='program_rates_not_negative'),
        ),
        migrations.AddConstraint(
            model_name='program',
            constraint=models.CheckConstraint(condition=django.db.models.lookups.Exact(django.db.models.functions.math.Mod(models.F('default_accredited_credits'), models.Value(Decimal('0.25'), output_field=models.DecimalField(decimal_places=2, max_digits=5)), output_field=models.DecimalField(decimal_places=2, max_digits=5)), models.Value(Decimal('0'), output_field=models.DecimalField(decimal_places=2, max_digits=5))), name='program_default_credits_quarter_multiple'),
        ),
        migrations.AddConstraint(
            model_name='program',
            constraint=models.CheckConstraint(condition=models.Q(('accreditation_year_end_month__gte', 1), ('accreditation_year_end_month__lte', 12)), name='program_year_end_month_valid'),
        ),
        migrations.AddConstraint(
            model_name='program',
            constraint=models.CheckConstraint(condition=models.Q(('accreditation_year_end_day__gte', 1), ('accreditation_year_end_day__lte', 31)), name='program_year_end_day_valid'),
        ),
        migrations.AddConstraint(
            model_name='programrole',
            constraint=models.UniqueConstraint(fields=('user', 'program'), name='programrole_one_per_program'),
        ),
    ]
