# Generated by Django 5.2.18 on 2026-10-06 20:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0001_initial'),
        ('rounds', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceUpload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_filename', models.CharField(max_length=255)),
                ('stored_path', models.CharField(help_text='Relative to UPLOAD_ROOT. Back this up with the database.', max_length=500)),
                ('sha256', models.CharField(max_length=64, unique=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('parsed_at', models.DateTimeField(blank=True, null=True)),
                ('parser_version', models.CharField(blank=True, max_length=50, null=True)),
                ('row_count', models.PositiveIntegerField(default=0)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploads', to='rounds.roundsevent')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('teams_upload', 'Teams upload'), ('manual', 'Manual'), ('room_roster', 'Room roster')], max_length=20)),
                ('parser_version', models.CharField(blank=True, max_length=50, null=True)),
                ('raw_display_name', models.CharField(blank=True, max_length=300, null=True)),
                ('raw_email', models.CharField(blank=True, max_length=320, null=True)),
                ('raw_participant_role', models.CharField(blank=True, max_length=50, null=True)),
                ('join_at', models.DateTimeField(blank=True, null=True)),
                ('leave_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, help_text='As recorded. For rows with join and leave times the credit calculation uses the times, not this.')),
                ('reason', models.TextField(blank=True, help_text="Required on every row that didn't come from Teams.", null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('match_method', models.CharField(choices=[('email_exact', 'Email (exact)'), ('email_alias', 'Email (alias)'), ('manual', 'Manual'), ('unmatched', 'Unmatched')], default='unmatched', max_length=20)),
                ('matched_at', models.DateTimeField(blank=True, null=True)),
                ('attributed_to', models.ForeignKey(blank=True, help_text='Room roster only: the row for the device this person sat at.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='room_roster_rows', to='attendance.attendancerecord')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_records', to='rounds.roundsevent')),
                ('matched_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attendance_records', to='people.person')),
                ('upload', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='records', to='attendance.attendanceupload')),
            ],
            options={
                'ordering': ['event', 'join_at', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceSupersession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('new', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supersedes', to='attendance.attendancerecord')),
                ('old', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='supersession', to='attendance.attendancerecord')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('old', models.F('new')), _negated=True), name='attendancesupersession_old_is_not_new')],
            },
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['event', 'person'], name='attendance__event_i_a6c04c_idx'),
        ),
        migrations.AddConstraint(
            model_name='attendancerecord',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('join_at__isnull', True), ('leave_at__isnull', True)), models.Q(('join_at__isnull', False), ('leave_at__isnull', False)), _connector='OR'), name='attendancerecord_times_both_or_neither'),
        ),
        migrations.AddConstraint(
            model_name='attendancerecord',
            constraint=models.CheckConstraint(condition=models.Q(('join_at__isnull', True), ('leave_at__gte', models.F('join_at')), _connector='OR'), name='attendancerecord_leave_after_join'),
        ),
        migrations.AddConstraint(
            model_name='attendancerecord',
            constraint=models.CheckConstraint(condition=models.Q(('source', 'teams_upload'), models.Q(('reason__isnull', False), models.Q(('reason', ''), _negated=True)), _connector='OR'), name='attendancerecord_non_teams_needs_reason'),
        ),
        migrations.AddConstraint(
            model_name='attendancerecord',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('source', 'teams_upload'), ('upload__isnull', False)), models.Q(models.Q(('source', 'teams_upload'), _negated=True), ('upload__isnull', True)), _connector='OR'), name='attendancerecord_upload_iff_teams'),
        ),
        migrations.AddConstraint(
            model_name='attendancerecord',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('attributed_to__isnull', False), ('source', 'room_roster')), models.Q(models.Q(('source', 'room_roster'), _negated=True), ('attributed_to__isnull', True)), _connector='OR'), name='attendancerecord_attributed_iff_room_roster'),
        ),
        migrations.AddConstraint(
            model_name='attendancerecord',
            constraint=models.CheckConstraint(condition=models.Q(('attributed_to__isnull', True), models.Q(('attributed_to', models.F('id')), _negated=True), _connector='OR'), name='attendancerecord_not_attributed_to_self'),
        ),
        migrations.AddConstraint(
            model_name='attendancerecord',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('match_method', 'unmatched'), ('person__isnull', True)), models.Q(('person__isnull', False), models.Q(('match_method', 'unmatched'), _negated=True)), _connector='OR'), name='attendancerecord_match_method_agrees_with_person'),
        ),
    ]
