# Generated by Django 5.2.18 on 2026-10-07 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_attendancerecord_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendanceupload',
            name='parse_warnings',
            field=models.JSONField(blank=True, default=list, help_text="What the parser noticed but did not stop for, such as Teams' own totals disagreeing with its rows."),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='raw_participant_role',
            field=models.CharField(blank=True, help_text="A Teams meeting permission, as written in the export. It says nothing about who presented and has no effect on credit. Presenters are the session's presenters.", max_length=50, null=True, verbose_name='Teams meeting role'),
        ),
    ]
