# Generated by Django 5.2.18 on 2026-10-07 13:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_attendanceupload_parse_warnings_and_more'),
        ('people', '0004_magic_links'),
        ('rounds', '0009_event_program_required'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionAttendanceDecision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('confirmed_minutes', models.PositiveIntegerField(help_text='What counts. Zero is a valid decision.')),
                ('proposed_minutes', models.PositiveIntegerField(help_text='What the system proposed at the time.')),
                ('basis', models.CharField(choices=[('sources_agree', 'Sources agree'), ('highest_claim', 'Highest claim, chosen by a person'), ('manual', 'Set by hand')], max_length=20)),
                ('based_on', models.JSONField(blank=True, default=dict, help_text="Each source's claim and the row ids, at sign-off.")),
                ('comment', models.TextField(blank=True, help_text='Required when the confirmed minutes differ from the proposal.')),
                ('confirmed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['session', 'person', '-confirmed_at'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='attendancerecord',
            name='attendancerecord_non_teams_needs_reason',
        ),
        migrations.RemoveConstraint(
            model_name='attendancerecord',
            name='attendancerecord_upload_iff_teams',
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='source',
            field=models.CharField(choices=[('teams_upload', 'Teams upload'), ('signin_sheet', 'Sign-in sheet'), ('qr_signin', 'QR sign-in'), ('manual', 'Manual'), ('room_roster', 'Room roster')], max_length=20),
        ),
        migrations.AddConstraint(
            model_name='attendancerecord',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('source__in', ['manual', 'room_roster']), _negated=True), models.Q(('reason__isnull', False), models.Q(('reason', ''), _negated=True)), _connector='OR'), name='attendancerecord_non_teams_needs_reason'),
        ),
        migrations.AddConstraint(
            model_name='attendancerecord',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('source__in', ['teams_upload', 'signin_sheet']), ('upload__isnull', False)), models.Q(models.Q(('source__in', ['teams_upload', 'signin_sheet']), _negated=True), ('upload__isnull', True)), _connector='OR'), name='attendancerecord_upload_iff_teams'),
        ),
        migrations.AddConstraint(
            model_name='attendancerecord',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('source__in', ['signin_sheet', 'qr_signin']), _negated=True), models.Q(('join_at__isnull', True), ('session__isnull', False)), _connector='OR'), name='attendancerecord_whole_session_sources_name_a_session'),
        ),
        migrations.AddConstraint(
            model_name='attendancerecord',
            constraint=models.UniqueConstraint(condition=models.Q(('source', 'qr_signin')), fields=('person', 'session'), name='attendancerecord_one_qr_scan_per_session'),
        ),
        migrations.AddField(
            model_name='sessionattendancedecision',
            name='confirmed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sessionattendancedecision',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_decisions', to='people.person'),
        ),
        migrations.AddField(
            model_name='sessionattendancedecision',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_decisions', to='rounds.session'),
        ),
        migrations.AddField(
            model_name='sessionattendancedecision',
            name='supersedes',
            field=models.OneToOneField(blank=True, help_text='The decision this one corrects.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='superseded_by', to='attendance.sessionattendancedecision'),
        ),
        migrations.AddIndex(
            model_name='sessionattendancedecision',
            index=models.Index(fields=['session', 'person'], name='attendance__session_b32bf4_idx'),
        ),
        migrations.AddConstraint(
            model_name='sessionattendancedecision',
            constraint=models.CheckConstraint(condition=models.Q(('confirmed_minutes', models.F('proposed_minutes')), models.Q(('comment', ''), _negated=True), _connector='OR'), name='sessionattendancedecision_change_needs_comment'),
        ),
        migrations.AddConstraint(
            model_name='sessionattendancedecision',
            constraint=models.CheckConstraint(condition=models.Q(('supersedes__isnull', True), models.Q(('supersedes', models.F('id')), _negated=True), _connector='OR'), name='sessionattendancedecision_not_own_correction'),
        ),
    ]
