# Generated by Django 5.2.18 on 2026-10-07 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_signin_sheet_is_typed_in'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sessionattendancedecision',
            options={'ordering': ['session', 'person', '-confirmed_at'], 'permissions': [('sign_off_attendance', 'Can sign off attendance')]},
        ),
    ]
