# Generated by Django 5.2.18 on 2026-10-07 14:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_signoff_permission'),
        ('people', '0004_magic_links'),
        ('rounds', '0009_event_program_required'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerecord',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='match_method',
            field=models.CharField(choices=[('email_exact', 'Email (exact)'), ('email_alias', 'Email (alias)'), ('manual', 'Manual'), ('self', 'Self (signed in and scanned)'), ('unmatched', 'Unmatched')], default='unmatched', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='attendancerecord',
            constraint=models.CheckConstraint(condition=models.Q(('created_by__isnull', False), ('source', 'qr_signin'), _connector='OR'), name='attendancerecord_created_by_unless_qr'),
        ),
    ]
